### PR TITLE
Main patches

### PR DESCRIPTION
**Pull request by lubennikovaav**
Split postgres changes to separate patches 1 commit per feature.

### CODE REVIEW

**Comment by hlinnaka** [comment]
LGTM in general.

There seem to be some small differences to 'main':
```
$ git diff  --stat origin/pr/48 origin/main
 src/backend/access/transam/xlog.c                |   4 +-
 src/backend/storage/buffer/bufmgr.c              |  40 ++++----
 src/bin/Makefile                                 |   4 +
 src/bin/pg_waldump/pg_waldump.c                  |  16 ++--
 src/bin/zenith_push/Makefile                     |  43 +++++++++
 src/bin/zenith_push/compat.c                     |  64 +++++++++++++
 src/bin/zenith_push/zenith_push.c                | 603 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/bin/zenith_push/zenith_push.h                |  59 ++++++++++++
 src/bin/zenith_restore/Makefile                  |  55 +++++++++++
 src/bin/zenith_restore/compat.c                  |  64 +++++++++++++
 src/bin/zenith_restore/zenith_restore.c          | 672 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/bin/zenith_restore/zenith_restore.h          |  63 +++++++++++++
 src/bin/zenith_slicedice/Makefile                |  59 ++++++++++++
 src/bin/zenith_slicedice/compat.c                |  64 +++++++++++++
 src/bin/zenith_slicedice/zenith_slicedice.c      | 498 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/bin/zenith_slicedice/zenith_slicedice.h      |  26 ++++++
 src/bin/zenith_slicedice/zenith_slicedice_main.c | 428 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/include/access/slru.h                        |   5 +
 src/include/access/xlogreader.h                  |   4 +-
 src/include/access/xlogutils.h                   |   6 ++
 src/include/storage/buf_internals.h              |   4 +
 src/test/perl/PostgresNode.pm                    |   6 +-
 22 files changed, 2758 insertions(+), 29 deletions(-)
```
I think this PR should end up in identical state as `main` branch, just with the commits rearranged differently. If those differences are intentional, let's commit them to the 'main' branch first.

The idea is to force-push this PR over 'main', right? Let's copy any worthwhile information from the old commit messages to the new ones, too.

After this is pushed, we will inevitably accumulate more changes. So every now and then, we will need to rebase and squash those subsequent commits, and force-push again. That's OK, we'll just need to coordinate it when we do that.

**Comment by hlinnaka** [comment]
I just opened https://github.com/zenithdb/postgres/pull/47 to remove a bunch of obsolete stuff. I'd propose that we push that first, and then rebase this. I think it should rebase fairly cleanly, as PR #47 just removes code. Some of the commits here will probably just evaporate away.

I think `0009_zenith_nonrelwalreader.patch` is also not needed anymore. It was used to apply the "sliced&diced" wal produced by the src/bin/zenith_* commands, but we don't use those anymore. We might need something similar again in the future, to apply non-rel WAL record, but let's get rid of any code we don't need right now, and add it back later if we need it.

**Comment by lubennikovaav** [comment]
Ok.
Most of the differences with main are just some debugging leftovers from previous experiments. 
Let's merge your PR and I'll rebase this.

> The idea is to force-push this PR over 'main', right?
yes. I was also planning to rebase this on top of master to catch up with upstream bugfixes.

**Comment by hlinnaka** [comment]
>  Let's merge your PR and I'll rebase this.

Ok. I'll push it as soon as CircleCI passes (https://github.com/zenithdb/zenith/pull/145), to make sure that I didn't accidentally remove something that's actually still needed.

**Comment by hlinnaka** [comment]
> > Let's merge your PR and I'll rebase this.
> 
> Ok. I'll push it as soon as CircleCI passes ([zenithdb/zenith#145](https://github.com/zenithdb/zenith/pull/145)), to make sure that I didn't accidentally remove something that's actually still needed.

Pushed

**Comment by lubennikovaav** [comment]
The updated patchset will be identical to main after cleanup in #49
Next steps are:
- clean up readme
- rebase to upstream master
- clean up zenith regression tests. (maybe move them to python tests if possible?)

But I'd rather push this part first.

**Review by hlinnaka — APPROVED** [review]
> The updated patchset will be identical to main after cleanup in #49
> Next steps are:
> 
>     * clean up readme
> 
>     * rebase to upstream master
> 
>     * clean up zenith regression tests. (maybe move them to python tests if possible?)
> 
> 
> But I'd rather push this part first.

+1, let's get this in. Let's move the old main branch out of the way as "main-old" or something, just in case we want to look back at the history. We almost certainly won't ever care about it, but wouldn't hurt to keep it.

**Pull request closed without merging**
