### PR TITLE
Relsize hash (patch by @kniznick) rebased

### PR DESCRIPTION
**Pull request by lubennikovaav**

### CODE REVIEW

**Review by knizhnik — APPROVED** [review]

**Comment by kelvich** [comment]
Thanks for rebasing!

Can you please post here `pgbench -S` numbers for a single backend with and without this patch?

**Comment by lubennikovaav** [comment]
1. CI fails on `pytest batch_pg_regress/test_isolation.py`
Also on my laptop it also hangs on `pytest batch_pg_regress/test_pg_regress.py`.

2. zenith_unlink() should reset cached value

3. I suppose that `createdb()` needs some special treatment too. Not sure, though.

**Comment by lubennikovaav** [comment]
After some debugging I found the problem:
`update_cached_relsize` may set incorrect value:
Let's say we have a relation of size 100 on pageserver and we requested page 10 and updated it. Then we'll cache relsize 10 instead of 100.

To fix this, we should always use nblocks returned from pageserver, if the entry wasn't found.
I'll fix it tomorrow morning.

**Comment by knizhnik** [comment]
> After some debugging I found the problem:
> `update_cached_relsize` may set incorrect value:
> Let's say we have a relation of size 100 on pageserver and we requested page 10 and updated it. Then we'll cache relsize 10 instead of 100.
> 
> To fix this, we should always use nblocks returned from pageserver, if the entry wasn't found.
> I'll fix it tomorrow morning.

Thank you for catching this bug.
I hope that the following version of update_cached_relsize should work:
```
static
void update_cached_relsize(SMgrRelation reln, ForkNumber forknum, BlockNumber size)
{
	if (relsize_hash_size > 0)
	{
		RelTag tag;
		RelSizeEntry* entry;

		tag.rnode = reln->smgr_rnode.node;
		tag.forknum = forknum;
		LWLockAcquire(relsize_lock, LW_EXCLUSIVE);
		entry = hash_search(relsize_hash, &tag, HASH_FIND, NULL);
		if (entry && entry->size < size)
			entry->size = size;
		LWLockRelease(relsize_lock);
	}
}
```

**Comment by kelvich** [comment]
> Thank you for catching this bug.
> I hope that the following version of update_cached_relsize should work:

I think that patch would effectively disable cache as the only HASH_ENTER left is in zenith_truncate().

**Comment by knizhnik** [comment]
> > Thank you for catching this bug.
> > I hope that the following version of update_cached_relsize should work:
> 
> I think that patch would effectively disable cache as the only HASH_ENTER left is in zenith_truncate().

You are right.
I think it is necessary to remove call of update_cached_relsize from zenith_wallog_page and instead of it 
call it in zenith_write after return from zenith_wallog_page and call set_cached_relsize in zenith_extend

**Comment by kelvich** [comment]
> > > Thank you for catching this bug.
> > > I hope that the following version of update_cached_relsize should work:
> > 
> > 
> > I think that patch would effectively disable cache as the only HASH_ENTER left is in zenith_truncate().
> 
> You are right.
> I think it is necessary to remove call of update_cached_relsize from zenith_wallog_page and instead of it
> call it in zenith_write after return from zenith_wallog_page and call set_cached_relsize in zenith_extend

My take on fixing it is here: https://github.com/zenithdb/postgres/pull/72/commits/7633c9b375da4c3ff42b093095c60fe991dfe20c

That fixed tests on my laptop, let's see what would happen with the whole tests suite.

**Comment by knizhnik** [comment]
I still think that it will be better to set_cached_relsize in zenith_extend. In this case we do not need to access pagse server at all to get size of new relation (created by this compute node instance).

**Pull request merged**
